sudo: true
language: python
python:
  - "3.4"

## http://superuser.com/questions/993718/can-i-install-java-8-on-travis-ci-for-a-python-project

# other answer:      
before_install:
  - sudo apt-get update
  - sudo apt-get install oracle-java8-installer
  - sudo update-java-alternatives -s java-8-oracle   

install:
  - "pip install pyyaml"

before_script:
  - mkdir -p bin
  - export PATH=$PATH:$PWD/bin
  - wget http://build.berkeleybop.org/userContent/owltools/owltools -O bin/owltools
  - wget http://build.berkeleybop.org/userContent/owltools/ontology-release-runner -O bin/ontology-release-runner
  - wget http://build.berkeleybop.org/userContent/owltools/owltools-runner-all.jar -O bin/owltools-runner-all.jar
  - wget http://build.berkeleybop.org/userContent/owltools/owltools-oort-all.jar -O bin/owltools-oort-all.jar
  - wget http://build.berkeleybop.org/job/robot/lastSuccessfulBuild/artifact/bin/robot -O bin/robot
  - wget http://build.berkeleybop.org/job/robot/lastSuccessfulBuild/artifact/bin/robot.jar -O bin/robot.jar
  - wget https://raw.githubusercontent.com/cmungall/pattern2owl/master/apply-pattern.py -O bin/apply-pattern.py
  - chmod +x bin/*

   
   
# command to run tests
script: make test

#after_success:
#  coveralls

# whitelist
branches:
  only:
    - master

notifications:
  email:
    - cjmungall@lbl.gov

